### ISSUE TITLE
Suggestion :: Save/Load Talent buttons

### ISSUE THREAD

**Issue by Artiodactyla** [Sonaza/FlashTalent#6]
Hi Sonaza/gamma91

Love this addon and have implemented it on all toons across my EU & US accounts.

One suggestion - I also use another talent addon to save/load class/spec specific builds [for single target/raid/AOE or other general uses [interrupt heavy fights etc]].

For ppl with multiple alts remembering the right build for the right situation is challenging :) and having the utility of it being available on screen at all times would be very useful

Would it be possible to add the feature to save/load builds as buttons on the main keybind interface?  For my money that makes it perfect !

The addon which does this currently is 'Talent Switch', but it adds buttons to the blizzard standard interface - I'm sure most of the LUA it uses to do this could be re-purposed

Great work amd tyvm

**Comment by Sonaza** [comment]
This is already a planned upcoming feature and on the issue tracker as task #5.

Just a matter of having time to do it.

**Comment by Artiodactyla** [comment]
excellent - thx Sonaza
